local M = {
  "lukas-reineke/indent-blankline.nvim",
  event = "VeryLazy",
  opts = {
    buftype_exclude = { "terminal", "nofile" },
    filetype_exclude = {
      "Trouble",
      "trouble",
      "noice",
      "help",
      "startify",
      "alpha",
      "dashboard",
      "lazy",
      "packer",
      "neogitstatus",
      "neo-tree",
      "mason.nvim",
    },
    char = "▏",
    show_current_context = true,
    show_current_context_start = true, -- underline first line
    use_treesitter = true,
    show_trailing_blankline_indent = false,
    context_patterns = {
      "class",
      "return",
      "function",
      "method",
      "^if",
      "^while",
      "jsx_element",
      "^for",
      "^object",
      "^table",
      "block",
      "arguments",
      "if_statement",
      "else_clause",
      "jsx_element",
      "jsx_self_closing_element",
      "try_statement",
      "catch_clause",
      "import_statement",
      "operation_type",
    },
  },
}

return M
